# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-28 18:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_auto_20160328_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2016, 3, 28, 18, 7, 44, 428511, tzinfo=utc)),
        ),
    ]
