# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-31 19:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import newapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_auto_20160401_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='corpus',
        ),
        migrations.RemoveField(
            model_name='students',
            name='corpus_calculated_uptill',
        ),
        migrations.RemoveField(
            model_name='students',
            name='current_sem_join_date',
        ),
        migrations.RemoveField(
            model_name='students',
            name='fee_last_submitted',
        ),
        migrations.AddField(
            model_name='students',
            name='student_photo',
            field=models.ImageField(blank=True, null=True, upload_to=newapp.models.student_photo_name),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2016, 3, 31, 19, 0, 13, 402396, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='students',
            name='room_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.Rooms'),
        ),
    ]
